services:
  postgres:
    image: 'postgres:16-alpine'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Se@12if!"
      POSTGRES_DB: ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    ports:
      - '8080:8080'
    env_file:
      - .docker.env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  data: